# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/electricity
spring.datasource.username=academy
spring.datasource.password=academy
# logging
logging.level.root=INFO
logging.level.fi.william.kwservice=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
# kilowatch
kilowatch.cors.allowed-origins=http://localhost:3333
